import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // 1. PASTE YOUR COMPLETE JSON ARRAY FROM paste.txt HERE
  const rawComponents = [
    // Copy the entire array from your paste.txt file here
    // It should start with [ and end with ]
    [
        {
          "manufacturer": "Shimano",
          "model": "CS-M9100",
          "year": "2018-2025",
          "weightGrams": 367,
          "msrp": 390.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 12, 14, 16, 18, 21, 24, 28, 33, 39, 45, 51],
          "freehubType": "MICRO_SPLINE",
          "spacing": null,
          "material": "Titanium, Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "CS-M8100",
          "year": "2019-2025",
          "weightGrams": 470,
          "msrp": 160.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 12, 14, 16, 18, 21, 24, 28, 33, 39, 45, 51],
          "freehubType": "MICRO_SPLINE",
          "spacing": null,
          "material": "Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "CS-M7100",
          "year": "2019-2025",
          "weightGrams": 534,
          "msrp": 105.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 12, 14, 16, 18, 21, 24, 28, 33, 39, 45, 51],
          "freehubType": "MICRO_SPLINE",
          "spacing": null,
          "material": "Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "CS-M6100",
          "year": "2020-2025",
          "weightGrams": 593,
          "msrp": 70.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 12, 14, 16, 18, 21, 24, 28, 33, 39, 45, 51],
          "freehubType": "MICRO_SPLINE",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "XX1 Eagle XG-1299",
          "year": "2016-2023",
          "weightGrams": 355,
          "msrp": 460.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 12, 14, 16, 18, 21, 24, 28, 32, 36, 42, 52],
          "freehubType": "SRAM_XD",
          "spacing": null,
          "material": "Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "X01 Eagle XG-1295",
          "year": "2016-2023",
          "weightGrams": 355,
          "msrp": 395.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 12, 14, 16, 18, 21, 24, 28, 32, 36, 42, 52],
          "freehubType": "SRAM_XD",
          "spacing": null,
          "material": "Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "GX Eagle XG-1275",
          "year": "2017-2023",
          "weightGrams": 450,
          "msrp": 220.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 12, 14, 16, 18, 21, 24, 28, 32, 36, 42, 52],
          "freehubType": "SRAM_XD",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "NX Eagle PG-1230",
          "year": "2018-2025",
          "weightGrams": 615,
          "msrp": 105.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [11, 13, 15, 17, 19, 21, 24, 28, 32, 36, 42, 50],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "SX Eagle PG-1210",
          "year": "2019-2025",
          "weightGrams": 720,
          "msrp": 80.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [11, 13, 15, 17, 19, 21, 24, 28, 32, 36, 42, 50],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "XX Eagle T-Type XS-1297",
          "year": "2023-2025",
          "weightGrams": 380,
          "msrp": 600.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 12, 14, 16, 18, 21, 24, 28, 32, 36, 42, 52],
          "freehubType": "SRAM_XD",
          "spacing": null,
          "material": "Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "X0 Eagle T-Type XS-1295",
          "year": "2023-2025",
          "weightGrams": 380,
          "msrp": 400.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 12, 14, 16, 18, 21, 24, 28, 32, 36, 42, 52],
          "freehubType": "SRAM_XD",
          "spacing": null,
          "material": "Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "GX Eagle T-Type XS-1275",
          "year": "2023-2025",
          "weightGrams": 445,
          "msrp": 250.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 12, 14, 16, 18, 21, 24, 28, 32, 36, 42, 52],
          "freehubType": "SRAM_XD",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "EX1 XG-899",
          "year": "2016-2022",
          "weightGrams": 360,
          "msrp": 390.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 8,
          "cogs": [11, 13, 15, 18, 24, 32, 40, 48],
          "freehubType": "SRAM_XD",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SunRace",
          "model": "CSMZ90",
          "year": "2018-2025",
          "weightGrams": 586,
          "msrp": 120.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [11, 13, 15, 17, 19, 21, 24, 28, 32, 36, 42, 50],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "e*thirteen",
          "model": "Helix R 12",
          "year": "2020-2025",
          "weightGrams": 345,
          "msrp": 299.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [9, 11, 13, 15, 17, 20, 23, 27, 31, 36, 42, 50],
          "freehubType": "SRAM_XD",
          "spacing": null,
          "material": "Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Garbaruk",
          "model": "12-Speed Cassette",
          "year": "2019-2025",
          "weightGrams": 323,
          "msrp": 260.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 12, 14, 16, 18, 21, 24, 28, 32, 37, 44, 52],
          "freehubType": "MICRO_SPLINE",
          "spacing": null,
          "material": "Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "Dura-Ace R9200",
          "year": "2021-2025",
          "weightGrams": 223,
          "msrp": 365.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [11, 12, 13, 14, 15, 16, 17, 19, 21, 24, 27, 30],
          "freehubType": "SHIMANO_HG_L2",
          "spacing": null,
          "material": "Titanium, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "Ultegra R8100",
          "year": "2021-2025",
          "weightGrams": 291,
          "msrp": 112.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [11, 12, 13, 14, 15, 17, 19, 21, 24, 27, 30, 34],
          "freehubType": "SHIMANO_HG_L2",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "105 R7100",
          "year": "2022-2025",
          "weightGrams": 361,
          "msrp": 70.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [11, 12, 13, 14, 15, 17, 19, 21, 24, 27, 30, 34],
          "freehubType": "SHIMANO_HG_L2",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "Dura-Ace R9100",
          "year": "2016-2021",
          "weightGrams": 175,
          "msrp": 250.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 11,
          "cogs": [11, 12, 13, 14, 15, 17, 19, 21, 23, 25, 28],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Titanium, Steel, Carbon",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "Ultegra R8000",
          "year": "2017-2021",
          "weightGrams": 232,
          "msrp": 80.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 11,
          "cogs": [11, 12, 13, 14, 15, 17, 19, 21, 23, 25, 28],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Steel, Carbon",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "105 R7000",
          "year": "2018-2025",
          "weightGrams": 284,
          "msrp": 55.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 11,
          "cogs": [11, 12, 13, 14, 16, 18, 20, 22, 25, 28, 32],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "Tiagra HG500-10",
          "year": "2016-2025",
          "weightGrams": 250,
          "msrp": 35.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 10,
          "cogs": [11, 12, 14, 16, 18, 20, 22, 25, 28, 32],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "Red XG-1290",
          "year": "2019-2025",
          "weightGrams": 178,
          "msrp": 380.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 11, 12, 13, 14, 15, 17, 19, 21, 24, 28, 33],
          "freehubType": "SRAM_XDR",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "Force XG-1270",
          "year": "2019-2025",
          "weightGrams": 238,
          "msrp": 190.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 11, 12, 13, 14, 15, 17, 19, 21, 24, 28, 33],
          "freehubType": "SRAM_XDR",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "Rival XG-1250",
          "year": "2021-2025",
          "weightGrams": 282,
          "msrp": 125.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 11, 12, 13, 15, 17, 19, 21, 24, 28, 32, 36],
          "freehubType": "SRAM_XDR",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "Force PG-1170",
          "year": "2015-2022",
          "weightGrams": 231,
          "msrp": 90.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 11,
          "cogs": [11, 12, 13, 14, 15, 16, 17, 19, 21, 23, 25],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "Rival PG-1130",
          "year": "2015-2025",
          "weightGrams": 271,
          "msrp": 70.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 11,
          "cogs": [11, 12, 13, 14, 15, 17, 19, 21, 24, 28, 32],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Super Record Wireless",
          "year": "2023-2025",
          "weightGrams": 210,
          "msrp": 595.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 11, 12, 13, 14, 15, 16, 17, 19, 21, 25, 29],
          "freehubType": "N3W",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Super Record",
          "year": "2018-2025",
          "weightGrams": 266,
          "msrp": 425.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [11, 12, 13, 14, 15, 16, 17, 19, 22, 25, 29, 32],
          "freehubType": "CAMPAGNOLO",
          "spacing": null,
          "material": "Titanium, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Record",
          "year": "2018-2025",
          "weightGrams": 283,
          "msrp": 320.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [11, 12, 13, 14, 15, 16, 17, 19, 22, 25, 29, 32],
          "freehubType": "CAMPAGNOLO",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Chorus",
          "year": "2019-2025",
          "weightGrams": 307,
          "msrp": 185.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [11, 12, 13, 14, 15, 16, 17, 19, 22, 25, 29, 32],
          "freehubType": "CAMPAGNOLO",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Rotor",
          "model": "12-Speed Cassette",
          "year": "2019-2025",
          "weightGrams": 236,
          "msrp": 400.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [11, 12, 13, 14, 15, 16, 17, 19, 21, 24, 27, 32],
          "freehubType": "ROTOR_HG",
          "spacing": null,
          "material": "Steel, Aluminum",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "CS-M5100-11",
          "year": "2019-2025",
          "weightGrams": 624,
          "msrp": 72.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 11,
          "cogs": [11, 13, 15, 17, 19, 21, 24, 28, 32, 37, 51],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX CS-HG700-11",
          "year": "2019-2025",
          "weightGrams": 379,
          "msrp": 85.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 11,
          "cogs": [11, 13, 15, 17, 19, 21, 23, 25, 27, 30, 34],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX CS-M8100-12",
          "year": "2023-2025",
          "weightGrams": 470,
          "msrp": 160.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 12, 14, 16, 18, 21, 24, 28, 33, 39, 45, 51],
          "freehubType": "MICRO_SPLINE",
          "spacing": null,
          "material": "Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX CS-R8101-12",
          "year": "2023-2025",
          "weightGrams": 345,
          "msrp": 112.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [11, 12, 13, 14, 15, 17, 19, 21, 24, 27, 30, 34],
          "freehubType": "SHIMANO_HG_L2",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Shimano",
          "model": "Linkglide CS-LG700-11",
          "year": "2022-2025",
          "weightGrams": 610,
          "msrp": 110.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 11,
          "cogs": [11, 13, 15, 17, 20, 23, 26, 30, 34, 39, 50],
          "freehubType": "SHIMANO_HG_L",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "XPLR XG-1271",
          "year": "2021-2025",
          "weightGrams": 295,
          "msrp": 225.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 11, 13, 15, 17, 19, 21, 24, 28, 32, 36, 44],
          "freehubType": "SRAM_XDR",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "XPLR XG-1251",
          "year": "2021-2025",
          "weightGrams": 412,
          "msrp": 150.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 12,
          "cogs": [10, 11, 13, 15, 17, 19, 21, 24, 28, 32, 36, 44],
          "freehubType": "SRAM_XDR",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Ekar",
          "year": "2020-2025",
          "weightGrams": 340,
          "msrp": 285.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 13,
          "cogs": [9, 10, 11, 12, 13, 14, 16, 18, 20, 23, 27, 32, 36],
          "freehubType": "N3W",
          "spacing": null,
          "material": "Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "Microshift",
          "model": "Advent X G-Series",
          "year": "2020-2025",
          "weightGrams": 424,
          "msrp": 70.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 10,
          "cogs": [11, 13, 15, 18, 21, 24, 28, 34, 40, 48],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SunRace",
          "model": "CSM983",
          "year": "2020-2025",
          "weightGrams": 475,
          "msrp": 80.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "CASSETTE",
          "speeds": 11,
          "cogs": [11, 13, 15, 18, 21, 24, 28, 32, 36, 42, 50],
          "freehubType": "SHIMANO_HG",
          "spacing": null,
          "material": "Aluminum, Steel",
          "maxTorque": null
        },
        {
          "manufacturer": "SRAM",
          "model": "XX SL Eagle T-Type",
          "year": "2023-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "32, 34, 36, 38",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "SRAM",
          "model": "XX/X0 Eagle T-Type",
          "year": "2023-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32, 34, 36, 38",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "SRAM",
          "model": "GX Eagle T-Type",
          "year": "2023-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32, 34",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Steel"
        },
        {
          "manufacturer": "SRAM",
          "model": "X-Sync 2 Eagle DM",
          "year": "2017-2024",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32, 34, 36, 38",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "SRAM",
          "model": "X-Sync 2 Eagle DM",
          "year": "2017-2024",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32, 34",
          "bcd": "DIRECT_MOUNT",
          "offset": 6.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "SRAM",
          "model": "X-Sync 2 Eagle",
          "year": "2017-2024",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "32, 34, 36, 38",
          "bcd": "104",
          "offset": null,
          "material": "Steel"
        },
        {
          "manufacturer": "SRAM",
          "model": "Red/Force AXS Flattop",
          "year": "2019-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "46/33, 48/35, 50/37",
          "bcd": "107",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "SRAM",
          "model": "Rival AXS Flattop",
          "year": "2021-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "46/33, 48/35",
          "bcd": "107",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "SRAM",
          "model": "AXS 1x Direct Mount",
          "year": "2019-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "38, 40, 42, 44, 46",
          "bcd": "DIRECT_MOUNT",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Shimano",
          "model": "XTR M9100",
          "year": "2018-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32, 34, 36, 38",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Shimano",
          "model": "XT M8100",
          "year": "2019-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "28, 30, 32, 34, 36",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Steel/Carbon"
        },
        {
          "manufacturer": "Shimano",
          "model": "SLX M7100",
          "year": "2019-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32, 34",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Steel"
        },
        {
          "manufacturer": "Shimano",
          "model": "Deore M6100",
          "year": "2020-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Steel"
        },
        {
          "manufacturer": "Shimano",
          "model": "Dura-Ace R9200",
          "year": "2021-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "50/34, 52/36, 54/40",
          "bcd": "110",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Shimano",
          "model": "Ultegra R8100",
          "year": "2021-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "50/34, 52/36",
          "bcd": "110",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Shimano",
          "model": "105 R7100",
          "year": "2022-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "50/34, 52/36",
          "bcd": "110",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Shimano",
          "model": "Ultegra R8000",
          "year": "2017-2022",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "46/36, 50/34, 52/36, 53/39",
          "bcd": "110",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Shimano",
          "model": "105 R7000",
          "year": "2018-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "46/36, 50/34, 52/36",
          "bcd": "110",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX RX820-1",
          "year": "2023-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "40, 42",
          "bcd": "110",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX RX810-1",
          "year": "2019-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "40, 42",
          "bcd": "110",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX RX810-2",
          "year": "2019-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "48/31",
          "bcd": "110/80",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX RX600-1",
          "year": "2020-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "40",
          "bcd": "110",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Race Face",
          "model": "Cinch Direct Mount",
          "year": "2016-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "28, 30, 32, 34, 36",
          "bcd": "CINCH",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Race Face",
          "model": "Cinch Direct Mount Steel",
          "year": "2018-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "28, 30, 32, 34",
          "bcd": "CINCH",
          "offset": 3.0,
          "material": "Steel"
        },
        {
          "manufacturer": "Wolf Tooth",
          "model": "Drop-Stop A",
          "year": "2016-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32, 34, 36, 38",
          "bcd": "104",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Wolf Tooth",
          "model": "Drop-Stop B",
          "year": "2022-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32, 34",
          "bcd": "96",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Wolf Tooth",
          "model": "SRAM Direct Mount",
          "year": "2017-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "28, 30, 32, 34, 36",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Absolute Black",
          "model": "Oval SRAM DM",
          "year": "2016-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "28, 30, 32, 34, 36",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Absolute Black",
          "model": "Oval Shimano DM",
          "year": "2018-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32, 34",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Absolute Black",
          "model": "Road 2X Oval",
          "year": "2017-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "50/34, 52/36",
          "bcd": "110",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "OneUp Components",
          "model": "Switch",
          "year": "2017-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "28, 30, 32, 34, 36",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Garbaruk",
          "model": "Direct Mount",
          "year": "2018-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "28, 30, 32, 34, 36",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Rotor",
          "model": "Q-Ring SRAM DM",
          "year": "2018-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32, 34, 36",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Rotor",
          "model": "Q-Ring Shimano DM",
          "year": "2018-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32, 34, 36",
          "bcd": "DIRECT_MOUNT",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Praxis Works",
          "model": "Wave Tech",
          "year": "2018-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "30, 32, 34",
          "bcd": "104",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Praxis Works",
          "model": "Cold Forged 2X",
          "year": "2016-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "50/34, 52/36",
          "bcd": "110",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Super Record",
          "year": "2018-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "50/34, 52/36, 53/39",
          "bcd": "145/112",
          "offset": null,
          "material": "Carbon/Alloy"
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Ekar",
          "year": "2020-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "38, 40, 42, 44",
          "bcd": "123",
          "offset": null,
          "material": "Aluminum"
        },
        {
          "manufacturer": "e*thirteen",
          "model": "Helix R Direct Mount",
          "year": "2020-2025",
          "weightGrams": null,
          "msrp": null,
          "verifiedWeight": null,
          "imageUrl": null,
          "category": "CHAINRING",
          "teeth": "28, 30, 32, 34, 36",
          "bcd": "e*thirteen DM",
          "offset": 3.0,
          "material": "Aluminum"
        },
        {
          "manufacturer": "SRAM",
          "model": "XX SL Eagle T-Type",
          "year": "2023-2025",
          "weightGrams": 240,
          "msrp": 150.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "SRAM",
          "model": "XX Eagle T-Type",
          "year": "2023-2025",
          "weightGrams": 247,
          "msrp": 125.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "SRAM",
          "model": "X0 Eagle T-Type",
          "year": "2023-2025",
          "weightGrams": 256,
          "msrp": 100.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "SRAM",
          "model": "GX Eagle T-Type",
          "year": "2023-2025",
          "weightGrams": 285,
          "msrp": 50.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "SRAM",
          "model": "XX1 Eagle",
          "year": "2016-2024",
          "weightGrams": 260,
          "msrp": 90.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "SRAM",
          "model": "X01 Eagle",
          "year": "2016-2024",
          "weightGrams": 264,
          "msrp": 65.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "SRAM",
          "model": "GX Eagle",
          "year": "2017-2024",
          "weightGrams": 270,
          "msrp": 33.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "SRAM",
          "model": "NX Eagle",
          "year": "2018-2025",
          "weightGrams": 272,
          "msrp": 26.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "SRAM",
          "model": "Red AXS Flattop",
          "year": "2019-2025",
          "weightGrams": 249,
          "msrp": 80.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 120
        },
        {
          "manufacturer": "SRAM",
          "model": "Force AXS Flattop",
          "year": "2019-2025",
          "weightGrams": 260,
          "msrp": 50.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 120
        },
        {
          "manufacturer": "SRAM",
          "model": "Rival AXS Flattop",
          "year": "2021-2025",
          "weightGrams": 266,
          "msrp": 35.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 120
        },
        {
          "manufacturer": "SRAM",
          "model": "PC-1170",
          "year": "2016-2023",
          "weightGrams": 256,
          "msrp": 45.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 11,
          "material": "steel",
          "links": 118
        },
        {
          "manufacturer": "SRAM",
          "model": "PC-1130",
          "year": "2016-2024",
          "weightGrams": 259,
          "msrp": 28.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 11,
          "material": "steel",
          "links": 118
        },
        {
          "manufacturer": "SRAM",
          "model": "PC-1110",
          "year": "2016-2024",
          "weightGrams": 262,
          "msrp": 15.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 11,
          "material": "steel",
          "links": 118
        },
        {
          "manufacturer": "SRAM",
          "model": "PC-1051",
          "year": "2010-2020",
          "weightGrams": 277,
          "msrp": 40.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 10,
          "material": "steel",
          "links": 114
        },
        {
          "manufacturer": "SRAM",
          "model": "PC-971",
          "year": "2008-2020",
          "weightGrams": 298,
          "msrp": 25.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 9,
          "material": "steel",
          "links": 114
        },
        {
          "manufacturer": "Shimano",
          "model": "CN-M9100",
          "year": "2018-2025",
          "weightGrams": 259,
          "msrp": 65.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "Shimano",
          "model": "CN-M8100",
          "year": "2019-2025",
          "weightGrams": 259,
          "msrp": 46.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "Shimano",
          "model": "CN-M7100",
          "year": "2019-2025",
          "weightGrams": 259,
          "msrp": 36.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "Shimano",
          "model": "CN-M6100",
          "year": "2020-2025",
          "weightGrams": 262,
          "msrp": 27.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "Shimano",
          "model": "CN-9000/HG901-11",
          "year": "2015-2024",
          "weightGrams": 247,
          "msrp": 50.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 11,
          "material": "steel",
          "links": 116
        },
        {
          "manufacturer": "Shimano",
          "model": "CN-HG701-11",
          "year": "2016-2025",
          "weightGrams": 257,
          "msrp": 40.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 11,
          "material": "steel",
          "links": 116
        },
        {
          "manufacturer": "Shimano",
          "model": "CN-HG601-11",
          "year": "2017-2025",
          "weightGrams": 260,
          "msrp": 30.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 11,
          "material": "steel",
          "links": 116
        },
        {
          "manufacturer": "Shimano",
          "model": "CN-HG54",
          "year": "2012-2022",
          "weightGrams": 278,
          "msrp": 25.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 10,
          "material": "steel",
          "links": 116
        },
        {
          "manufacturer": "Shimano",
          "model": "CN-LG500",
          "year": "2022-2025",
          "weightGrams": 257,
          "msrp": 30.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 11,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Ekar C13",
          "year": "2020-2025",
          "weightGrams": 242,
          "msrp": 55.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 13,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Record 12",
          "year": "2018-2025",
          "weightGrams": 241,
          "msrp": 75.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 114
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Chorus 12",
          "year": "2019-2025",
          "weightGrams": 252,
          "msrp": 50.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 114
        },
        {
          "manufacturer": "KMC",
          "model": "X12",
          "year": "2019-2025",
          "weightGrams": 268,
          "msrp": 45.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "KMC",
          "model": "X12 DLC",
          "year": "2020-2025",
          "weightGrams": 260,
          "msrp": 130.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "KMC",
          "model": "X11SL",
          "year": "2016-2025",
          "weightGrams": 239,
          "msrp": 85.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 11,
          "material": "steel",
          "links": 118
        },
        {
          "manufacturer": "KMC",
          "model": "X11",
          "year": "2016-2025",
          "weightGrams": 257,
          "msrp": 38.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 11,
          "material": "steel",
          "links": 118
        },
        {
          "manufacturer": "KMC",
          "model": "e12",
          "year": "2020-2025",
          "weightGrams": 272,
          "msrp": 60.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "Wippermann Connex",
          "model": "12SX",
          "year": "2020-2025",
          "weightGrams": 270,
          "msrp": 90.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "stainless steel",
          "links": 126
        },
        {
          "manufacturer": "Wippermann Connex",
          "model": "11SX",
          "year": "2016-2025",
          "weightGrams": 264,
          "msrp": 80.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 11,
          "material": "stainless steel",
          "links": 118
        },
        {
          "manufacturer": "YBN",
          "model": "SLA1210-Ti",
          "year": "2019-2025",
          "weightGrams": 225,
          "msrp": 110.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 126
        },
        {
          "manufacturer": "FSA",
          "model": "K-Force WE 12s",
          "year": "2019-2025",
          "weightGrams": 250,
          "msrp": 75.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "CHAIN",
          "speeds": 12,
          "material": "steel",
          "links": 118
        },
        {
          "manufacturer": "SRAM",
          "model": "XX SL Eagle Transmission",
          "year": "2023-2025",
          "weightGrams": 440,
          "msrp": 650.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "XX Eagle Transmission",
          "year": "2023-2025",
          "weightGrams": 465,
          "msrp": 650.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "X0 Eagle Transmission",
          "year": "2023-2025",
          "weightGrams": 475,
          "msrp": 550.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "GX Eagle Transmission",
          "year": "2023-2025",
          "weightGrams": 489,
          "msrp": 400.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "X0 Eagle Mechanical Transmission",
          "year": "2024-2025",
          "weightGrams": 468,
          "msrp": 300.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "GX Eagle Mechanical Transmission",
          "year": "2024-2025",
          "weightGrams": 480,
          "msrp": 165.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "XX1 Eagle AXS",
          "year": "2019-2024",
          "weightGrams": 373,
          "msrp": 750.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "X01 Eagle AXS",
          "year": "2019-2024",
          "weightGrams": 388,
          "msrp": 550.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "GX Eagle AXS",
          "year": "2021-2025",
          "weightGrams": 468,
          "msrp": 370.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "XX1 Eagle",
          "year": "2016-2024",
          "weightGrams": 264,
          "msrp": 480.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "X01 Eagle",
          "year": "2016-2024",
          "weightGrams": 276,
          "msrp": 245.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "GX Eagle",
          "year": "2017-2024",
          "weightGrams": 290,
          "msrp": 125.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "NX Eagle",
          "year": "2018-2025",
          "weightGrams": 339,
          "msrp": 115.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 50,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "SX Eagle",
          "year": "2019-2025",
          "weightGrams": 385,
          "msrp": 85.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 50,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "Red eTap AXS",
          "year": "2019-2025",
          "weightGrams": 327,
          "msrp": 710.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 33,
          "cageLength": "MEDIUM"
        },
        {
          "manufacturer": "SRAM",
          "model": "Force eTap AXS",
          "year": "2019-2025",
          "weightGrams": 348,
          "msrp": 490.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 36,
          "cageLength": "MEDIUM"
        },
        {
          "manufacturer": "SRAM",
          "model": "Rival eTap AXS",
          "year": "2021-2025",
          "weightGrams": 366,
          "msrp": 255.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 36,
          "cageLength": "MEDIUM"
        },
        {
          "manufacturer": "SRAM",
          "model": "Red XPLR eTap AXS",
          "year": "2021-2025",
          "weightGrams": 313,
          "msrp": 725.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 44,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "Force XPLR eTap AXS",
          "year": "2021-2025",
          "weightGrams": 327,
          "msrp": 515.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 44,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "Rival XPLR eTap AXS",
          "year": "2021-2025",
          "weightGrams": 340,
          "msrp": 265.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 44,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "Apex AXS",
          "year": "2023-2025",
          "weightGrams": 378,
          "msrp": 290.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 36,
          "cageLength": "MEDIUM"
        },
        {
          "manufacturer": "SRAM",
          "model": "Apex XPLR AXS",
          "year": "2023-2025",
          "weightGrams": 352,
          "msrp": 320.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 44,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "Apex Eagle",
          "year": "2023-2025",
          "weightGrams": 479,
          "msrp": 150.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "Force 1",
          "year": "2015-2022",
          "weightGrams": 261,
          "msrp": 240.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 11,
          "maxCapacity": 42,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "Rival 1",
          "year": "2015-2023",
          "weightGrams": 269,
          "msrp": 120.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 11,
          "maxCapacity": 42,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "SRAM",
          "model": "Apex 1",
          "year": "2016-2023",
          "weightGrams": 314,
          "msrp": 80.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 11,
          "maxCapacity": 42,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Shimano",
          "model": "Deore XT M8150 Di2",
          "year": "2023-2025",
          "weightGrams": 385,
          "msrp": 550.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 11,
          "maxCapacity": 51,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Shimano",
          "model": "XTR M9100",
          "year": "2018-2024",
          "weightGrams": 241,
          "msrp": 430.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 51,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Shimano",
          "model": "XT M8100",
          "year": "2019-2024",
          "weightGrams": 284,
          "msrp": 121.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 51,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Shimano",
          "model": "XT M8000",
          "year": "2015-2020",
          "weightGrams": 275,
          "msrp": 110.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 11,
          "maxCapacity": 46,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Shimano",
          "model": "SLX M7100",
          "year": "2019-2024",
          "weightGrams": 316,
          "msrp": 86.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 51,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Shimano",
          "model": "Deore M6100",
          "year": "2020-2025",
          "weightGrams": 320,
          "msrp": 60.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 51,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Shimano",
          "model": "CUES RD-U6000",
          "year": "2023-2025",
          "weightGrams": 350,
          "msrp": 70.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 11,
          "maxCapacity": 50,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Shimano",
          "model": "Dura-Ace R9250 Di2",
          "year": "2021-2025",
          "weightGrams": 215,
          "msrp": 815.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 34,
          "cageLength": "ONE SIZE"
        },
        {
          "manufacturer": "Shimano",
          "model": "Ultegra R8150 Di2",
          "year": "2021-2025",
          "weightGrams": 262,
          "msrp": 450.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 34,
          "cageLength": "ONE SIZE"
        },
        {
          "manufacturer": "Shimano",
          "model": "105 R7150 Di2",
          "year": "2022-2025",
          "weightGrams": 302,
          "msrp": 280.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 36,
          "cageLength": "ONE SIZE"
        },
        {
          "manufacturer": "Shimano",
          "model": "Ultegra R8000",
          "year": "2017-2022",
          "weightGrams": 200,
          "msrp": 95.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 11,
          "maxCapacity": 34,
          "cageLength": "MEDIUM"
        },
        {
          "manufacturer": "Shimano",
          "model": "105 R7000",
          "year": "2018-2024",
          "weightGrams": 225,
          "msrp": 56.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 11,
          "maxCapacity": 34,
          "cageLength": "MEDIUM"
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX RX820",
          "year": "2023-2025",
          "weightGrams": 270,
          "msrp": 122.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 36,
          "cageLength": "MEDIUM"
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX RX822",
          "year": "2023-2025",
          "weightGrams": 290,
          "msrp": 122.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 51,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX RX815 Di2",
          "year": "2019-2024",
          "weightGrams": 288,
          "msrp": 335.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 11,
          "maxCapacity": 34,
          "cageLength": "MEDIUM"
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX RX817 Di2",
          "year": "2019-2024",
          "weightGrams": 322,
          "msrp": 350.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 11,
          "maxCapacity": 42,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX RX810",
          "year": "2019-2025",
          "weightGrams": 255,
          "msrp": 120.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 11,
          "maxCapacity": 34,
          "cageLength": "MEDIUM"
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX RX812",
          "year": "2019-2025",
          "weightGrams": 267,
          "msrp": 125.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 11,
          "maxCapacity": 42,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Shimano",
          "model": "GRX RX400",
          "year": "2019-2025",
          "weightGrams": 303,
          "msrp": 60.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 10,
          "maxCapacity": 36,
          "cageLength": "MEDIUM"
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Super Record Wireless",
          "year": "2023-2025",
          "weightGrams": 295,
          "msrp": 850.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 30,
          "cageLength": "ONE SIZE"
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Ekar",
          "year": "2020-2025",
          "weightGrams": 275,
          "msrp": 270.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 13,
          "maxCapacity": 44,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Record",
          "year": "2018-2025",
          "weightGrams": 216,
          "msrp": 400.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 32,
          "cageLength": "MEDIUM"
        },
        {
          "manufacturer": "Campagnolo",
          "model": "Chorus",
          "year": "2020-2025",
          "weightGrams": 220,
          "msrp": 265.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 34,
          "cageLength": "MEDIUM"
        },
        {
          "manufacturer": "Box Components",
          "model": "Two Prime 9",
          "year": "2017-2025",
          "weightGrams": 290,
          "msrp": 125.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 9,
          "maxCapacity": 50,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "TRP",
          "model": "TR12",
          "year": "2021-2025",
          "weightGrams": 282,
          "msrp": 240.00,
          "verifiedWeight": true,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 50,
          "cageLength": "LONG"
        },
        {
          "manufacturer": "Garbaruk",
          "model": "RD Cage",
          "year": "2019-2025",
          "weightGrams": 48,
          "msrp": 160.00,
          "verifiedWeight": false,
          "imageUrl": null,
          "category": "DERAILLEUR",
          "speeds": 12,
          "maxCapacity": 52,
          "cageLength": "LONG"
        }
      ]
  ]

  // Convert your data to the database format
  const components = rawComponents[0].map(item => {
    // Handle the year format conversion
    const yearStr = typeof item.year === 'string' ? item.year : String(item.year)
    const yearInt = parseInt(yearStr.split('-')[0])
    
    // Create base component data
    const baseComponent = {
      manufacturer: item.manufacturer,
      model: item.model,
      year: yearInt,
      weightGrams: item.weightGrams,
      msrp: item.msrp,
      verifiedWeight: item.verifiedWeight ?? false, // Default to false if null/undefined
      imageUrl: item.imageUrl,
      category: item.category
    }
    
    // Add component-specific data based on category
    let specificData: any = {}
    
    if (item.category === 'CASSETTE') {
      specificData.cassette = {
        speeds: item.speeds,
        cogs: item.cogs,
        freehubType: item.freehubType,
        spacing: item.spacing,
        material: item.material,
        maxTorque: item.maxTorque
      }
    } else if (item.category === 'CHAINRING') {
      specificData.chainring = {
        teeth: typeof item.teeth === 'string' ? parseInt(item.teeth.split(',')[0]) : item.teeth,
        bcd: item.bcd === 'DIRECT_MOUNT' ? null : (item.bcd ? parseFloat(item.bcd) : null),
        offset: item.offset,
        material: item.material
      }
    } else if (item.category === 'CHAIN') {
      specificData.chain = {
        speeds: item.speeds,
        material: item.material,
        links: item.links
      }
    } else if (item.category === 'DERAILLEUR') {
      specificData.derailleur = {
        speeds: item.speeds,
        maxCapacity: item.maxCapacity,
        cageLength: item.cageLength === 'ONE SIZE' ? 'ONE_SIZE' : item.cageLength
      }
    }
    
    return { ...baseComponent, ...specificData }
  })

  // 2. COMPONENT DATA STRUCTURE - How to save each component
  for (const componentData of components) {
    // Extract the specific component type data
    const { cassette, chainring, chain, derailleur, hub, tire, wheel, ...baseComponent } = componentData

    // Create or update the base component (handle duplicates)
    const component = await prisma.component.upsert({
      where: {
        manufacturer_model_year: {
          manufacturer: baseComponent.manufacturer,
          model: baseComponent.model,
          year: baseComponent.year
        }
      },
      update: baseComponent,
      create: baseComponent
    })

    // Then create the specific component data if it exists
    if (cassette) {
      await prisma.cassette.upsert({
        where: { componentId: component.id },
        update: { ...cassette },
        create: {
          componentId: component.id,
          ...cassette
        }
      })
    }

    if (chainring) {
      await prisma.chainring.upsert({
        where: { componentId: component.id },
        update: { ...chainring },
        create: {
          componentId: component.id,
          ...chainring
        }
      })
    }

    if (chain) {
      await prisma.chain.upsert({
        where: { componentId: component.id },
        update: { ...chain },
        create: {
          componentId: component.id,
          ...chain
        }
      })
    }

    if (derailleur) {
      await prisma.derailleur.upsert({
        where: { componentId: component.id },
        update: { ...derailleur },
        create: {
          componentId: component.id,
          ...derailleur
        }
      })
    }

    if (hub) {
      await prisma.hub.create({
        data: {
          componentId: component.id,
          ...hub
        }
      })
    }

    if (tire) {
      await prisma.tire.create({
        data: {
          componentId: component.id,
          ...tire
        }
      })
    }

    if (wheel) {
      await prisma.wheel.create({
        data: {
          componentId: component.id,
          ...wheel
        }
      })
    }

    console.log(`Created component: ${component.manufacturer} ${component.model}`)
  }
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })